const wordList = [
  { word: "air", hint: "the invisible gaseous" },
  { word: "idea", hint: "a thought or suggestion" },
  { word: "server", hint: "related to computer or system" },
  { word: "svg", hint: "a vector image format" },
  { word: "jpeg", hint: "a small image file format" },
  { word: "search", hint: "act to find something" },
  { word: "water", hint: "Covers most of the human body" },
  { word: "fingers", hint: "give something with them" },
  { word: "python", hint: "programming language" },
  { word: "guitar", hint: "a musical instrument" },
  { word: "aim", hint: "a perpose or intention" },
  { word: "venus", hint: "planet of our solar system" },
  {
    word: "map",
    hint: "you can use it and find exacly place in mobile and pc ..",
  },
  { word: "gold", hint: "a yellow precious metal" },
  { word: "golang", hint: "programming language" },
  { word: "venice", hint: "famous city of waters" },
  { word: "mysql", hint: "a relation database system" },
  { word: "nepal", hint: "a developing country" },
  { word: "flute", hint: "a musical instrument" },
  { word: "crypto", hint: "related to cryptocurrency" },
  { word: "tesla", hint: "unit of magnetic flux density " },
  { word: "rocket", hint: "space vehicle or missile" },
  { word: "mars", hint: "second smallest planet" },
  { word: "apple", hint: "mobile manufacture brand" },
  { word: "proxy", hint: "related to server application" },
];
